// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalaReuniao.Api.Infrastructure;

#nullable disable

namespace SalaReuniao.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110194443_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.ClienteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.ResponsavelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.ReuniaoAgendadaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSalaReuniao")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdSalaReuniao");

                    b.ToTable("Reunioes");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.SalaDeReuniaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdEndereco")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdResponsavel")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdResponsavel");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.SalaServicoOferecidoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSala")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdServico")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdSala");

                    b.HasIndex("IdServico");

                    b.ToTable("ServicosOferecidos");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.ServicoAgendadoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdReuniaoAgendada")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSalaServicoOferecido")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdReuniaoAgendada");

                    b.HasIndex("IdSalaServicoOferecido");

                    b.ToTable("ServicosAgendados");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.ServicoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdResponsavel")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdResponsavel");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.ReuniaoAgendadaEntity", b =>
                {
                    b.HasOne("SalaReuniao.Api.Infrastructure.Entities.ClienteEntity", "Cliente")
                        .WithMany("ReunioesAgendadas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalaReuniao.Api.Infrastructure.Entities.SalaDeReuniaoEntity", "SalaReuniao")
                        .WithMany("ReunioesAgendadas")
                        .HasForeignKey("IdSalaReuniao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("SalaReuniao");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.SalaDeReuniaoEntity", b =>
                {
                    b.HasOne("SalaReuniao.Api.Infrastructure.Entities.ResponsavelEntity", "Responsavel")
                        .WithMany("Salas")
                        .HasForeignKey("IdResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.SalaServicoOferecidoEntity", b =>
                {
                    b.HasOne("SalaReuniao.Api.Infrastructure.Entities.SalaDeReuniaoEntity", "Sala")
                        .WithMany("ServicosOferecidos")
                        .HasForeignKey("IdSala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalaReuniao.Api.Infrastructure.Entities.ServicoEntity", "Servico")
                        .WithMany("ServicosOferecidos")
                        .HasForeignKey("IdServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.ServicoAgendadoEntity", b =>
                {
                    b.HasOne("SalaReuniao.Api.Infrastructure.Entities.ReuniaoAgendadaEntity", "ReuniaoAgendada")
                        .WithMany("ServicosAgendados")
                        .HasForeignKey("IdReuniaoAgendada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalaReuniao.Api.Infrastructure.Entities.SalaServicoOferecidoEntity", "SalaServicoOferecido")
                        .WithMany("ServicosAgendados")
                        .HasForeignKey("IdSalaServicoOferecido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReuniaoAgendada");

                    b.Navigation("SalaServicoOferecido");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.ServicoEntity", b =>
                {
                    b.HasOne("SalaReuniao.Api.Infrastructure.Entities.ResponsavelEntity", "Responsavel")
                        .WithMany("ServicosCadastrados")
                        .HasForeignKey("IdResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.ClienteEntity", b =>
                {
                    b.Navigation("ReunioesAgendadas");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.ResponsavelEntity", b =>
                {
                    b.Navigation("Salas");

                    b.Navigation("ServicosCadastrados");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.ReuniaoAgendadaEntity", b =>
                {
                    b.Navigation("ServicosAgendados");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.SalaDeReuniaoEntity", b =>
                {
                    b.Navigation("ReunioesAgendadas");

                    b.Navigation("ServicosOferecidos");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.SalaServicoOferecidoEntity", b =>
                {
                    b.Navigation("ServicosAgendados");
                });

            modelBuilder.Entity("SalaReuniao.Api.Infrastructure.Entities.ServicoEntity", b =>
                {
                    b.Navigation("ServicosOferecidos");
                });
#pragma warning restore 612, 618
        }
    }
}
